### ISSUE TITLE
Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by Josef-Vonasek** [WaveBeans/wavebeans#111]
I have followed the instructions and added wavebeans into my gradle project.
```kotlin
val wavebeans_version = "0.0.1.1"

repositories {
    mavenCentral()
    maven {
        name = "Bintray WaveBeans"
        url = uri("https://dl.bintray.com/wavebeans/wavebeans")
    }

}

dependencies {
    implementation ("io.wavebeans:exe:$wavebeans_version")
    implementation ("io.wavebeans:lib:$wavebeans_version")
    implementation ("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
}
```

However, building gradle fails with the following message:

`Could not GET 'https://dl.bintray.com/wavebeans/wavebeans/io/wavebeans/exe/0.0.1.1/exe-0.0.1.1.pom'. Received status code 403 from server: Forbidden`

**Comment by asubb** [comment]
Hi @Josef-Vonasek,

Yes, the bintray stopped operating as a whole, I need to migrate to another Maven repository. What version specifically you intended to use? `0.0.1.1` or you are fine with the latest one `0.3.0`? I would need to publish certain ones.

**Comment by Josef-Vonasek** [comment]
Actually, 0.3 is fine. I thought 0.0.1.1 was the latest, as it was the version of the packages.

**Comment by asubb** [comment]
@Josef-Vonasek I've created the issue to publish artifacts to maven central https://issues.sonatype.org/browse/OSSRH-69197

Meanwhile, you may use the local maven. To do this, you may clone the repository and publish the artifact locally:

```sh
./gradlew publishToMavenLocal
```

and then add Maven Local to your gradle file:

```kotlin
repositories {
    mavenLocal()
}
```

The version it publishes under is populated inside `gradle.properties`, for the master branch it is `0.3.0`

That wouldn't be required anymore
```kotlin
maven {
        name = "Bintray WaveBeans"
        url = uri("https://dl.bintray.com/wavebeans/wavebeans")
    }
```

**Comment by asubb** [comment]
The most recent version is now 0.3.1, but functionally it is no different from 0.3.0. Both versions are in Maven Central now.
